import {test} from 'node:test';import assert from 'node:assert/strict';
import {APP,users,session,verify,validate} from './netlify/functions/hairhouse.mjs';
const source=APP.slice(APP.indexOf('function match('),APP.indexOf('const $='));
const {forecast,match,extract,duplicates,receiptAlerts}=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport {forecast,match,extract,duplicates,receiptAlerts};').toString('base64'));
const data=(items=[])=>({version:1,balance:{cents:100000,date:'2026-10-07'},items});const item=(p={})=>({id:'1',kind:'invoice',supplier:'Example',reference:'I1',cents:10000,date:'2026-10-08',status:'confirmed',notes:'',...p});
const cases=[['invoice', [item()],90000],['review excluded',[item({status:'review'})],100000],['paid before balance excluded',[item({status:'paid',paidDate:'2026-10-06'})],100000],['paid after balance deducted',[item({status:'paid',paidDate:'2026-10-08'})],90000],['estimated order',[item({kind:'order',status:'estimated'})],90000],['order matched once',[item({id:'po',kind:'order'}),item({id:'inv',orderId:'po'})],90000],['partial invoices',[item({id:'po',kind:'order'}),item({id:'inv',orderId:'po',cents:4000})],90000],['credit reduces payable',[item(),item({id:'c',kind:'credit',cents:2000})],92000],['credit does not restore order',[item({id:'po',kind:'order'}),item({orderId:'po'}),item({id:'c',kind:'credit',orderId:'po',cents:2000})],92000],['sales excluded from conservative',[item({kind:'inflow',cents:50000})],100000],['cancelled excluded',[item({status:'cancelled'})],100000],['overdue reserved',[item({date:'2026-10-01'})],90000]];
for(const [name,items,min] of cases)test(name,()=>assert.equal(forecast(data(items)).minimum,min));
test('12 weeks',()=>assert.equal(forecast(data()).weeks.length,12));test('negative cash visible',()=>assert.equal(forecast(data([item({cents:200000})])).minimum,-100000));test('duplicates case insensitive',()=>assert.equal(duplicates([item(),item({id:'2',reference:'i1'})]).length,1));test('pack mismatch',()=>assert.ok(match({...item(),lines:[{sku:'a',qty:3,pack:6}]},{...item(),lines:[{sku:'a',qty:6,pack:1}]}).length));test('quantity matches',()=>assert.deepEqual(match({...item(),lines:[{sku:'a',qty:3,pack:6}]},{...item(),lines:[{sku:'a',qty:18,pack:1}]}),[]));test('late receipts',()=>assert.deepEqual(receiptAlerts([item({receiptExpected:'2026-09-20',lines:[{sku:'a',qty:3,pack:6,received:6}]})],'2026-10-07'),['1']));test('received not late',()=>assert.deepEqual(receiptAlerts([item({receiptExpected:'2026-09-20',lines:[{sku:'a',qty:3,pack:6,received:18}]})],'2026-10-07'),[]));test('valid data',()=>assert.equal(validate(data([item()])).version,1));test('invalid dates',()=>assert.throws(()=>validate(data([item({date:'2026-02-30'})]))));test('invalid negative',()=>assert.throws(()=>validate(data([item({cents:-1})]))));test('wrong supplier match',()=>assert.throws(()=>validate(data([item({id:'po',kind:'order'}),item({orderId:'po',supplier:'other'})]))));test('missing configuration fails closed',()=>assert.deepEqual(users({}),[]));test('third user rejected',()=>assert.deepEqual(users({HAIRHOUSE_USERS:'[{},{},{}]'}),[]));test('session integrity and expiry',()=>{const s='x'.repeat(48),u=[{email:'a@example.com'}],token=session('a@example.com',s,0);assert.equal(verify(token,s,u,100),'a@example.com');assert.equal(verify(token+'x',s,u,100),null);assert.equal(verify(token,s,u,9*3600e3),null);assert.equal(verify(token,s,[],100),null);});test('generic extraction is review candidate',()=>{const r=extract('Invoice Number INV-12 Due Date 05/11/2026 Total Due $1,200.00');assert.equal(r.reference,'INV-12');assert.equal(r.cents,120000);assert.equal(r.date,'2026-11-05');});

test('paid linked invoice does not reopen order reserve',()=>assert.equal(forecast(data([item({id:'po',kind:'order'}),item({id:'paid',orderId:'po',status:'paid',paidDate:'2026-10-06'})])).minimum,100000));
test('credit owed not spendable',()=>assert.equal(forecast(data([item({kind:'creditOwed',cents:50000})])).minimum,100000));
const predictionSource=APP.slice(APP.indexOf('function match('),APP.indexOf('const $='));const {bankHistory,historyPrediction}=await import('data:text/javascript;base64,'+Buffer.from(predictionSource+'\nexport {bankHistory,historyPrediction};').toString('base64'));
const rows=[];let balance=100000;for(let n=0;n<35;n++){const date=new Date(Date.UTC(2026,7,3+n)).toISOString().slice(0,10);const d=date.split('-').reverse().join('/');balance+=1000;rows.unshift(`${d},10.00,Direct Credit ANZ Worldline,${balance/100}`);}
const model=bankHistory(rows.join('\n')),predictionData={version:1,balance:{cents:100000,date:'2026-09-06'},items:[],historyModel:model};
test('complete weeks only',()=>{assert.equal(model.weeks,4);assert.equal(model.start,'2026-08-03');assert.equal(model.end,'2026-08-30');});
test('sales prediction deterministic',()=>{assert.equal(historyPrediction(predictionData).next7,107000);assert.equal(historyPrediction(predictionData).next30,130000);});
test('bad balance chain rejected',()=>assert.throws(()=>bankHistory(rows.join('\n').replace('1350','9999'))));
test('committed floor not added twice',()=>{const m={...model,daily:model.daily.map(d=>({...d,'other debits':1000}))};const items=[{id:'i',kind:'expense',status:'confirmed',date:'2026-09-07',cents:10000,supplier:'Example',reference:'',notes:''}];assert.equal(historyPrediction({...predictionData,historyModel:m,items}).next7,97000);});
test('history is optional',()=>assert.equal(historyPrediction({...predictionData,historyModel:null}),null));
test('invalid history blocked server side',()=>assert.throws(()=>validate({...predictionData,historyModel:{...model,daily:[]}})));
test('margin windows use trailing days of actual settlements',()=>{const w=model.margin.windows;assert.deepEqual(w.map(x=>x.days),[7,14,30]);assert.equal(w[0].sales,7*1000);assert.equal(w[2].sales,30*1000);assert.equal(w[0].rent,0);});
test('margin windows validated server side',()=>{assert.throws(()=>validate({...predictionData,historyModel:{...model,margin:{windows:[{days:9}]}}}));validate(predictionData);});
test('margin months cover calendar months with partial flags',()=>{const mo=model.margin.months;assert.deepEqual(mo.map(x=>x.key),['2026-08','2026-09']);assert.equal(mo[0].partial,true);assert.equal(mo[0].start,'2026-08-03');assert.equal(mo[0].sales,29*1000);assert.equal(mo[1].partial,true);assert.equal(mo[1].sales,6*1000);});
test('margin months validated server side',()=>assert.throws(()=>validate({...predictionData,historyModel:{...model,margin:{...model.margin,months:[{key:'bad'}]}}})));
test('margin windows reconcile to bank balance change',()=>{for(const w of [...model.margin.windows,...model.margin.months])assert.equal(w.sales+w.credits-w.staff-w.insurance-w.suppliers-w.royalty-w.rent-w.other-(w.marketing||0)-(w.loans||0)-(w.tax||0)-(w.utilities||0)-(w.fees||0)-(w.coffee||0)-(w.personal||0),w.change);assert.equal(model.margin.windows[0].change,7*1000);});
const mkRows=(from,to,fn)=>{const out=[];for(let n=from;n<=to;n++)out.unshift(fn(n));return out;};
{const all=rows.slice();// newest first, 35 rows
 const A=all.slice(0,20).join('\n'),B=all.slice(15).join('\n');
 test('two overlapping CSVs merge to the single-file model',()=>{const m=bankHistory([B,A]);assert.equal(m.rows,35);assert.equal(m.merge.duplicates,5);assert.deepEqual({...m,merge:undefined},{...model,merge:undefined});});
 test('adjacent CSVs with no overlap still join by balance chain',()=>{const m=bankHistory([all.slice(0,20).join('\n'),all.slice(20).join('\n')]);assert.equal(m.rows,35);assert.equal(m.merge.duplicates,0);});
 test('CSVs with a gap are rejected',()=>assert.throws(()=>bankHistory([all.slice(0,15).join('\n'),all.slice(20).join('\n')]),/do not join/));
 test('contained duplicate file adds nothing',()=>assert.equal(bankHistory([all.join('\n'),all.slice(5,25).join('\n')]).rows,35));
 {const full=[];let bal=100000;const oldestFirst=[];for(let n=0;n<30;n++){const d=new Date(Date.UTC(2026,7,3+Math.floor(n/2))).toISOString().slice(0,10).split('-').reverse().join('/');const amt=n===10||n===11?-4:10;bal+=amt*100;oldestFirst.push(`${d},${amt.toFixed(2)},${amt<0?'Card fee':'ANZ Worldline'},${bal/100}`);}
 const nf=oldestFirst.reverse();// newest first, rows 19 and 18 are the two identical fees
 test('identical same-day fees both survive an overlapping merge',()=>{const m=bankHistory([nf.slice(0,20).join('\n'),nf.slice(8).join('\n')]);assert.equal(m.rows,30);assert.equal(m.merge.duplicates,12);});
 test('same fee on same day in both files is not double counted or dropped',()=>{const m=bankHistory([nf.slice(0,22).join('\n'),nf.slice(8).join('\n')]);assert.equal(m.rows,30);});
}
}
{const {parseCashTenders,mergeCash,cashIn}=await import('data:text/javascript;base64,'+Buffer.from(predictionSource+'\nexport {parseCashTenders,mergeCash,cashIn};').toString('base64'));
const cell=(t,v)=>`<Cell><Data ss:Type="${t}">${v}</Data></Cell>`,hdr=['Date','Location','Visa','Cash','Total Cash &amp; Cards'].map(x=>cell('String',x)).join('');
const xml=(rows,loc='Store A')=>`<Workbook><Worksheet><Table><Row>${hdr}</Row>${rows.map(([d,c])=>`<Row>${cell('DateTime',d+'T00:00:00')}${cell('String',loc)}${cell('Number','.00')}${cell('Number',c)}${cell('Number',c)}</Row>`).join('')}<Row>${cell('String','Overall Total')}${cell('String','')}${cell('Number','0')}${cell('Number','999')}</Row></Table></Worksheet></Workbook>`;
test('cash tenders parsed from NetSuite xml, total row ignored',()=>{const c=parseCashTenders(xml([['2026-09-01','100.50'],['2026-09-03','.00'],['2026-09-04','20']]));assert.equal(c.start,'2026-09-01');assert.equal(c.end,'2026-09-04');assert.deepEqual(c.days,[['2026-09-01',10050],['2026-09-03',0],['2026-09-04',2000]]);});
test('cash tenders rejects wrong file and several stores',()=>{assert.throws(()=>parseCashTenders('hello'));assert.throws(()=>parseCashTenders('<Workbook><Row><Cell><Data ss:Type="String">Date</Data></Cell></Row></Workbook>'),/No Date and Cash/);const two=xml([['2026-09-01','1']],'A').replace('</Table>','')+'';assert.throws(()=>parseCashTenders(xml([['2026-09-01','1']]).replace('</Row></Table>',`</Row><Row>${cell('DateTime','2026-09-02T00:00:00')}${cell('String','Store B')}${cell('Number','0')}${cell('Number','5')}</Row></Table>`)),/several locations/);});
test('cash merge overrides overlap, replaces on gap, window sums',()=>{const a=parseCashTenders(xml([['2026-09-01','10'],['2026-09-02','20']])),b=parseCashTenders(xml([['2026-09-02','25'],['2026-09-03','30']]));const r=mergeCash(a,b);assert.equal(r.replaced,false);assert.deepEqual(r.merged.days,[['2026-09-01',1000],['2026-09-02',2500],['2026-09-03',3000]]);assert.equal(cashIn(r.merged,'2026-09-02','2026-09-03').cents,5500);assert.equal(cashIn(r.merged,'2026-08-30','2026-09-03').covered,false);assert.equal(mergeCash(a,parseCashTenders(xml([['2026-10-09','1']]))).replaced,true);});
test('cash sales validated server side',()=>{assert.throws(()=>validate({...predictionData,cashSales:{version:1,start:'2026-09-01',end:'2026-09-02',days:[['bad',1]]}}));validate({...predictionData,cashSales:{version:1,start:'2026-09-01',end:'2026-09-02',days:[['2026-09-01',1]]}});});
}
{const descs=[['-100.00','Direct Debit 403450 Commonwealth Bank Loan Rypmt to 062703'],['-50.00','Direct Debit 313094 HAIRHOUSE WAREHO MARK3026853'],['-4.00','HUANG INVENTIONS P/L WETHERILL PAR AU Card xx1366'],['-30.00','TAX OFFICE PAYMENTS NetBank BPAY'],['-20.00','Direct Debit 523295 AFTERPAY AUSTRAL'],['-10.00','Transfer To Unknown Vendor Pty'],['-500.00','THE HILLS GRAMMA 27845']];
 const lines=[];let bal=1000000;const oldest=[];for(let n=0;n<28;n++){const d=new Date(Date.UTC(2026,8,1+n)).toISOString().slice(0,10).split('-').reverse().join('/');const x=n<7?descs[n]:['10.00','Direct Credit ANZ Worldline'];bal=Math.round(bal+Number(x[0])*100);oldest.push(`${d},${x[0]},${x[1]},${bal/100}`);}
 const m=bankHistory(oldest.reverse().join('\n')),w=m.margin.months[0];
 test('new cost categories classify recurring payees',()=>{assert.equal(w.loans,10000);assert.equal(w.marketing,5000);assert.equal(w.coffee,400);assert.equal(w.tax,3000);assert.equal(w.fees,2000);assert.equal(w.other,1000);assert.equal(w.personal,50000);assert.equal(w.sales+w.credits-w.personal-w.loans-w.marketing-w.coffee-w.tax-w.fees-w.other-w.staff-w.insurance-w.suppliers-w.royalty-w.rent,w.change);});
}
import {splitTx} from './netlify/functions/hairhouse.mjs';
test('splitTx removes transactions from the stored workspace copy only',()=>{const d={version:1,historyModel:{margin:{windows:[],tx:[['2026-10-01',-5,'','A']]}}};const s=splitTx(d);assert.equal(s.tx.length,1);assert.equal('tx' in s.data.historyModel.margin,false);assert.equal('tx' in d.historyModel.margin,true);assert.equal(splitTx({version:1}).tx,null);});
