import {test} from 'node:test';import assert from 'node:assert/strict';
import {APP,users,session,verify,validate} from './netlify/functions/hairhouse.mjs';
const source=APP.slice(APP.indexOf('function match('),APP.indexOf('const $='));
const {forecast,match,extract,duplicates,receiptAlerts}=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport {forecast,match,extract,duplicates,receiptAlerts};').toString('base64'));
const data=(items=[])=>({version:1,balance:{cents:100000,date:'2026-10-07'},items});const item=(p={})=>({id:'1',kind:'invoice',supplier:'Example',reference:'I1',cents:10000,date:'2026-10-08',status:'confirmed',notes:'',...p});
const cases=[['invoice', [item()],90000],['review excluded',[item({status:'review'})],100000],['paid before balance excluded',[item({status:'paid',paidDate:'2026-10-06'})],100000],['paid after balance deducted',[item({status:'paid',paidDate:'2026-10-08'})],90000],['estimated order',[item({kind:'order',status:'estimated'})],90000],['order matched once',[item({id:'po',kind:'order'}),item({id:'inv',orderId:'po'})],90000],['partial invoices',[item({id:'po',kind:'order'}),item({id:'inv',orderId:'po',cents:4000})],90000],['credit reduces payable',[item(),item({id:'c',kind:'credit',cents:2000})],92000],['credit does not restore order',[item({id:'po',kind:'order'}),item({orderId:'po'}),item({id:'c',kind:'credit',orderId:'po',cents:2000})],92000],['sales excluded from conservative',[item({kind:'inflow',cents:50000})],100000],['cancelled excluded',[item({status:'cancelled'})],100000],['overdue reserved',[item({date:'2026-10-01'})],90000]];
for(const [name,items,min] of cases)test(name,()=>assert.equal(forecast(data(items)).minimum,min));
test('12 weeks',()=>assert.equal(forecast(data()).weeks.length,12));test('negative cash visible',()=>assert.equal(forecast(data([item({cents:200000})])).minimum,-100000));test('duplicates case insensitive',()=>assert.equal(duplicates([item(),item({id:'2',reference:'i1'})]).length,1));test('pack mismatch',()=>assert.ok(match({...item(),lines:[{sku:'a',qty:3,pack:6}]},{...item(),lines:[{sku:'a',qty:6,pack:1}]}).length));test('quantity matches',()=>assert.deepEqual(match({...item(),lines:[{sku:'a',qty:3,pack:6}]},{...item(),lines:[{sku:'a',qty:18,pack:1}]}),[]));test('late receipts',()=>assert.deepEqual(receiptAlerts([item({receiptExpected:'2026-09-20',lines:[{sku:'a',qty:3,pack:6,received:6}]})],'2026-10-07'),['1']));test('received not late',()=>assert.deepEqual(receiptAlerts([item({receiptExpected:'2026-09-20',lines:[{sku:'a',qty:3,pack:6,received:18}]})],'2026-10-07'),[]));test('valid data',()=>assert.equal(validate(data([item()])).version,1));test('invalid dates',()=>assert.throws(()=>validate(data([item({date:'2026-02-30'})]))));test('invalid negative',()=>assert.throws(()=>validate(data([item({cents:-1})]))));test('wrong supplier match',()=>assert.throws(()=>validate(data([item({id:'po',kind:'order'}),item({orderId:'po',supplier:'other'})]))));test('missing configuration fails closed',()=>assert.deepEqual(users({}),[]));test('third user rejected',()=>assert.deepEqual(users({HAIRHOUSE_USERS:'[{},{},{}]'}),[]));test('session integrity and expiry',()=>{const s='x'.repeat(48),u=[{email:'a@example.com'}],token=session('a@example.com',s,0);assert.equal(verify(token,s,u,100),'a@example.com');assert.equal(verify(token+'x',s,u,100),null);assert.equal(verify(token,s,u,9*3600e3),null);assert.equal(verify(token,s,[],100),null);});test('generic extraction is review candidate',()=>{const r=extract('Invoice Number INV-12 Due Date 05/11/2026 Total Due $1,200.00');assert.equal(r.reference,'INV-12');assert.equal(r.cents,120000);assert.equal(r.date,'2026-11-05');});

test('paid linked invoice does not reopen order reserve',()=>assert.equal(forecast(data([item({id:'po',kind:'order'}),item({id:'paid',orderId:'po',status:'paid',paidDate:'2026-10-06'})])).minimum,100000));
test('credit owed not spendable',()=>assert.equal(forecast(data([item({kind:'creditOwed',cents:50000})])).minimum,100000));
