[build]
  publish = "build/"
  command = "python deploy.py --build-only"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Response = {404}}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
